"""Bausteine der geführten Meditationen in freier Länge (Karte „Eigene Länge").

Schema je Art: e1, e2 = Einstieg · m1..m8 = Mitte (werden gleichmäßig über die
Länge verteilt, bei 3 Min also m1 + m8) · ms = „ich bin still" vor der langen
Stille · s1, s2 = Schluss. Bei 1 Minute nimmt die App nur e1 + ms + s1, darum
sind diese drei kurz gehalten.

Stimmen: ElevenLabs v3, Sarah (w) / Brian (m) — siehe tools/flex_bauen.py.
"""

ARTEN = {
    "gedanken": {
        "titel": "Gedanken beobachten", "kurz": "wie Wolken ziehen lassen",
        "e1": "Setz dich so hin, dass du eine Weile bleiben kannst. Lass die Augen zufallen oder senk den Blick. Ein paar Atemzüge, nichts weiter.",
        "e2": "Diese Meditation hat nur eine Aufgabe: bemerken, was in deinem Kopf passiert, ohne dich einzumischen. Gedanken kommen. Du siehst zu.",
        "m1": "Stell dir vor, du sitzt am Ufer eines Flusses. Auf dem Wasser treiben Blätter vorbei. Jedes Blatt ist ein Gedanke. Du bleibst am Ufer.",
        "m2": "Ein Gedanke taucht auf. Vielleicht eine Erinnerung, ein Plan, eine Sorge. Du musst ihn nicht zu Ende denken. Nur bemerken: da ist ein Gedanke.",
        "m3": "Wenn du merkst, dass du mitten in einer Geschichte steckst, ist das kein Fehler. Genau dieser Moment des Bemerkens ist die Übung. Dann zurück ans Ufer.",
        "m4": "Du kannst dem Gedanken leise ein Etikett geben. Planen. Erinnern. Bewerten. Ein Wort genügt. Dann lässt du ihn weiterziehen.",
        "m5": "Manche Gedanken sind laut und wollen sofort etwas von dir. Auch die dürfen vorbeitreiben. Nichts muss jetzt entschieden werden.",
        "m6": "Vielleicht ist gerade gar kein Gedanke da. Auch das ist in Ordnung. Dann spürst du einfach den Atem, bis der nächste kommt.",
        "m7": "Achte darauf, wie ein Gedanke von selbst verblasst, wenn du ihn nicht festhältst. Er braucht deine Aufmerksamkeit, um zu bleiben.",
        "m8": "Du bist nicht deine Gedanken. Du bist der, der sie bemerkt. Das ist ein kleiner, aber wichtiger Unterschied.",
        "ms": "Ich bin jetzt eine Weile still. Bleib am Ufer und schau zu, was vorbeikommt.",
        "s1": "Lass das Bild vom Fluss langsam los. Spür wieder den Boden unter dir und das Gewicht deines Körpers.",
        "s2": "Ein tiefer Atemzug. Wenn du bereit bist, öffne die Augen. Die Gedanken gehen weiter, und du kannst ihnen jetzt etwas gelassener zusehen.",
    },
    "koerperscan": {
        "titel": "Körperscan", "kurz": "Fuß bis Kopf",
        "e1": "Leg dich hin oder setz dich bequem. Lass die Augen zufallen. Ein paar ruhige Atemzüge, und der Körper darf schwer werden.",
        "e2": "Wir wandern jetzt mit der Aufmerksamkeit durch den Körper, von den Füßen bis zum Kopf. Es geht nicht darum, etwas zu verändern. Nur zu spüren, was da ist.",
        "m1": "Beginne bei den Füßen. Die Zehen, die Fußsohlen, die Fersen. Vielleicht spürst du Wärme, Kribbeln, den Druck der Unterlage. Oder nichts. Auch das ist eine Wahrnehmung.",
        "m2": "Wandere zu den Unterschenkeln und Knien. Die Waden, die Schienbeine. Lass sie einfach liegen, so schwer sie wollen.",
        "m3": "Die Oberschenkel und das Becken. Ein großer, tragender Bereich. Spür, wo dein Körper aufliegt und gehalten wird.",
        "m4": "Der Bauch. Er hebt sich beim Einatmen und senkt sich beim Ausatmen. Du musst nichts daran tun. Nur zusehen, wie er sich bewegt.",
        "m5": "Der untere Rücken und der Brustkorb. Vielleicht spürst du den Herzschlag. Vielleicht Stellen, die fester sind als andere. Lass sie sein.",
        "m6": "Die Hände. Die Finger, die Handflächen, die Handrücken. Dann die Arme hinauf bis zu den Schultern. Die Schultern dürfen ein Stück nach unten sinken.",
        "m7": "Der Nacken und der Hals. Der Kiefer. Oft halten wir hier fest, ohne es zu merken. Lass die Zähne ein wenig auseinander.",
        "m8": "Das Gesicht. Die Augen hinter den Lidern, die Stirn, die Schläfen. Die Kopfhaut bis zum Hinterkopf. Alles darf weich werden.",
        "ms": "Spür jetzt den ganzen Körper auf einmal, von den Füßen bis zum Kopf. Ich bin eine Weile still.",
        "s1": "Komm langsam zurück. Beweg die Finger und die Zehen. Vielleicht magst du dich strecken.",
        "s2": "Nimm einen tiefen Atemzug. Und wenn du bereit bist, öffne die Augen.",
    },
    "loslassen": {
        "titel": "Loslassen", "kurz": "Spannung abgeben",
        "e1": "Mach es dir bequem, im Sitzen oder Liegen. Lass die Augen zufallen. Du hast jetzt nichts mehr zu erledigen.",
        "e2": "In dieser Meditation geht es ums Loslassen. Nicht mit Kraft, sondern indem du bemerkst, wo du festhältst, und die Hand öffnest.",
        "m1": "Beginne mit dem Atem. Lass das Ausatmen etwas länger werden als das Einatmen. Mit jedem Ausatmen darf ein bisschen Spannung mitgehen.",
        "m2": "Spür deine Schultern. Ziehst du sie hoch, ohne es zu wollen? Lass sie sinken. Ein Stück, und noch ein Stück.",
        "m3": "Die Hände. Vielleicht sind die Finger leicht gekrümmt, als hielten sie noch etwas. Lass sie sich öffnen und weich liegen.",
        "m4": "Der Kiefer und die Stirn. Lass die Zähne auseinander, die Zunge locker. Die Stirn wird glatt. Das Gesicht muss jetzt nichts ausdrücken.",
        "m5": "Vielleicht trägst du etwas aus dem Tag mit dir. Ein Gespräch, eine Aufgabe, einen Ärger. Du musst es nicht lösen. Leg es für die Dauer dieser Meditation neben dich.",
        "m6": "Stell dir vor, du atmest in die Stelle, die sich am engsten anfühlt. Und beim Ausatmen wird sie ein wenig weiter. Nicht ganz. Ein wenig reicht.",
        "m7": "Alles, was du jetzt nicht ändern kannst, darf so sein, wie es ist. Wenigstens für die nächsten Minuten.",
        "m8": "Der Körper wird schwer und ruhig. Du wirst getragen. Es gibt nichts, was du jetzt halten musst.",
        "ms": "Ich bin jetzt eine Weile still. Lass mit jedem Ausatmen etwas mehr los.",
        "s1": "Bevor du zurückkommst, spür noch einmal, wie es sich anfühlt, wenn weniger gehalten wird. Das kannst du mitnehmen.",
        "s2": "Beweg langsam die Finger und Zehen. Ein tiefer Atemzug. Und öffne die Augen, wenn du so weit bist.",
    },
    "wohlwollen": {
        "titel": "Wohlwollen", "kurz": "für dich und andere",
        "e1": "Setz dich bequem hin und lass die Augen zufallen. Ein paar ruhige Atemzüge. Lass das Gesicht weich werden.",
        "e2": "Diese Meditation übt Wohlwollen. Ein freundliches Gefühl, zuerst dir selbst gegenüber, dann anderen. Es muss sich nicht groß anfühlen. Die Absicht zählt.",
        "m1": "Denk an einen Moment, in dem du dich wohl gefühlt hast. Bei jemandem, an einem Ort, oder einfach so. Lass dieses Gefühl kurz da sein.",
        "m2": "Richte es nun auf dich selbst. Innerlich, in deinen Worten, etwa so: Möge ich gesund sein. Möge ich ruhig sein. Möge es mir gut gehen.",
        "m3": "Wenn sich das seltsam anfühlt, ist das normal. Du sagst es trotzdem. Wie zu einem Freund, der es gerade braucht.",
        "m4": "Jetzt denk an einen Menschen, den du gern hast. Stell dir sein Gesicht vor. Möge dieser Mensch gesund sein. Möge er ruhig sein. Möge es ihm gut gehen.",
        "m5": "Dann jemand, den du kaum kennst. Die Person an der Kasse, jemand aus der Nachbarschaft. Auch diesem Menschen wünschst du dasselbe. Möge es ihm gut gehen.",
        "m6": "Wenn du magst, denk an jemanden, mit dem es gerade schwierig ist. Du musst nichts verzeihen. Nur den Wunsch aussprechen, dass auch dieser Mensch Ruhe findet.",
        "m7": "Und zuletzt alle Menschen, in deiner Stadt und darüber hinaus. Mögen sie gesund sein. Mögen sie ruhig sein. Möge es ihnen gut gehen.",
        "m8": "Spür, wie sich dein Körper dabei anfühlt. Vielleicht wärmer, vielleicht weiter. Vielleicht auch nicht. Beides ist in Ordnung.",
        "ms": "Ich bin jetzt eine Weile still. Bleib bei dem freundlichen Wunsch, für wen auch immer er gerade da ist.",
        "s1": "Kehr noch einmal zu dir zurück. Möge ich gesund sein. Möge ich ruhig sein. Möge es mir gut gehen.",
        "s2": "Ein tiefer Atemzug. Wenn du bereit bist, öffne die Augen. Nimm ein bisschen von dieser Freundlichkeit mit in den Tag.",
    },
    "weite": {
        "titel": "Offene Weite", "kurz": "alles da sein lassen",
        "e1": "Setz dich aufrecht und bequem. Die Augen können zufallen oder halb offen bleiben. Ein paar Atemzüge, ohne etwas zu wollen.",
        "e2": "In dieser Meditation gibt es keinen Gegenstand, auf den du dich konzentrierst. Du machst die Aufmerksamkeit weit und lässt alles da sein, was gerade da ist.",
        "m1": "Beginne mit den Geräuschen. Nahe und ferne. Du musst sie nicht benennen. Lass sie kommen und wieder gehen, wie sie wollen.",
        "m2": "Nimm den Raum um dich wahr. Vor dir, hinter dir, über dir. Du sitzt mitten drin, und der Raum ist größer als du.",
        "m3": "Spür den Körper als Ganzes. Nicht Teil für Teil, sondern die ganze Gestalt auf einmal, wie sie hier sitzt und atmet.",
        "m4": "Gedanken tauchen auf und vergehen, Empfindungen kommen und gehen, Geräusche entstehen und verklingen. Du bist der Raum, in dem das alles geschieht.",
        "m5": "Wenn die Aufmerksamkeit eng wird und sich an etwas festmacht, mach sie wieder weit. Wie ein Blick, der vom Detail zurück auf die ganze Landschaft geht.",
        "m6": "Es gibt hier nichts zu erreichen. Keinen besseren Zustand, den du herstellen müsstest. Nur dieses offene Dasein, jetzt.",
        "m7": "Vielleicht merkst du eine Ruhe, die nicht davon abhängt, dass es ruhig ist. Sie ist einfach da, unter allem anderen.",
        "m8": "Lass auch die Anstrengung los, aufmerksam zu sein. Die Wahrnehmung passiert von selbst. Du kannst dich darin ausruhen.",
        "ms": "Ich bin jetzt eine Weile still. Bleib weit und lass alles da sein.",
        "s1": "Komm langsam zurück in den Raum. Spür den Boden, den Sitz, deine Hände.",
        "s2": "Ein tiefer Atemzug. Öffne die Augen und lass den Blick einen Moment weit bleiben, bevor du weitergehst.",
    },
    "gehen": {
        "titel": "Gehmeditation", "kurz": "Schritt für Schritt",
        "e1": "Steh einen Moment still, bevor du losgehst. Spür beide Füße auf dem Boden und das Gewicht, das sich verteilt. Die Augen bleiben offen, der Blick ruht ein paar Meter vor dir.",
        "e2": "Geh jetzt los, langsamer als sonst. In dieser Meditation gibt es kein Ziel. Der Weg selbst ist die Übung: jeden Schritt spüren, einen nach dem anderen.",
        "m1": "Achte auf die Fußsohlen. Wie die Ferse aufsetzt, wie das Gewicht nach vorn rollt, wie sich die Zehen vom Boden lösen. Bei jedem Schritt.",
        "m2": "Spür, wie das Gewicht von einem Bein aufs andere wandert. Einen Moment lang trägt nur ein Fuß. Dann der andere. Dein Körper macht das seit Jahren, ohne dass du hinschaust.",
        "m3": "Du kannst innerlich mitsprechen: Heben. Setzen. Heben. Setzen. Wenn die Worte stören, lass sie weg und bleib beim Spüren.",
        "m4": "Lass die Arme locker mitschwingen. Die Schultern sinken. Der Blick bleibt weich, ohne etwas zu suchen.",
        "m5": "Nimm die Umgebung dazu: die Luft auf der Haut, Geräusche, das Licht. Du musst nichts davon benennen. Es zieht vorbei, während du gehst.",
        "m6": "Wenn die Gedanken abwandern, und das werden sie, komm einfach mit dem nächsten Schritt zurück. Der Boden ist immer da.",
        "m7": "Probier für ein paar Schritte, noch etwas langsamer zu werden. So langsam, dass du fast das Gleichgewicht suchst. Dann wieder dein Tempo.",
        "m8": "Der Atem geht von selbst, im Takt der Schritte oder daneben. Du musst ihn nicht steuern. Nur gehen, und dabei da sein.",
        "ms": "Ich bin jetzt eine Weile still. Geh weiter, Schritt für Schritt.",
        "s1": "Bleib jetzt langsam stehen. Spür noch einmal beide Füße auf dem Boden, so wie am Anfang.",
        "s2": "Ein Atemzug im Stehen. Wenn du weitergehst, darf ein bisschen von dieser Aufmerksamkeit mitkommen, in deinem normalen Tempo.",
    },
}
